---
- name: Make sure .config exists
  become: false
  file:
    path: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0700"
    state: directory
  tags:
    - dirs

- name: Create sw dir
  become: false
  file:
    path: "{{ sw_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0700"
    state: directory
  tags: dirs
