---
- name: Make sure .config exists
  become: false
  file:
    path: "/home/{{ user }}/.config"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0700"
    state: directory
  tags:
    - dirs

- name: copy xdg config
  become: false
  template:
    src: user-dirs.dirs.j2
    dest: "/home/{{ user }}/.config/user-dirs.dirs"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  tags:
    - dirs

- name: Create xdg dirs
  become: false
  file:
    path: "/home/{{ user }}/{{ item.value }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0750"
    state: directory
  loop: "{{ xdg | dict2items }}"
  tags:
    - dirs

- name: create wallpapers and scrots dir
  become: false
  file:
    path: "{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0755"
    state: directory
  with_items:
    - "/home/{{ user }}/{{ xdg.pictures }}/wallpapers"
    - "/home/{{ user }}/{{ xdg.pictures }}/scrots"
  tags:
    - dirs

- name: check for default fedora wallpaper
  stat:
    path: /usr/share/backgrounds/default.png
  register: default_wallpaper
  tags:
    - dirs

- name: check if wallpapers exist
  find:
    paths: "/home/{{ user }}/{{ xdg.pictures }}/wallpapers"
  register: wallpapers_found
  tags:
    - dirs

- name: copy default wallpaper if there are no others
  become: false
  copy:
    src: /usr/share/backgrounds/default.png
    dest: "/home/{{ user }}/{{ xdg.pictures }}/wallpapers/default.png"
    remote_src: yes
  when: default_wallpaper.stat.exists and wallpapers_found.matched == 0
  tags:
    - dirs

- name: Create sw dir
  become: false
  file:
    path: "{{ sw_dir }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0700"
    state: directory
  tags:
    - dirs
