- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
  tags:
    - docker

- name: Adding user "{{ user }}" to docker group
  user:
    name: "{{ user }}"
    groups: docker 
    append: yes
  tags:
    - docker

