- name: Load package list
  include_vars:
    file: "packages-fedora.yml"
  ignore_errors: true
  tags: packages

- name: Install packages
  ansible.builtin.dnf:
    name: "{{ install_packages }}"
  tags: packages

- name: Uninstall packages
  ansible.builtin.dnf:
    name: "{{ uninstall_packages }}"
    state: absent
  tags: packages
