- name: Add google cloud repository
  become: yes
  yum_repository:
    name: gcloud
    description: Google Cloud SDK
    file: google-cloud-sdk
    baseurl: https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64
    gpgkey: |
      https://packages.cloud.google.com/yum/doc/yum-key.gpg
      https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: yes
  when: 
    - install_gcloud 
    - ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - gcloud

- name: Install gcloud
  become: yes
  dnf:
    name: google-cloud-sdk
    state: present
  when: 
    - install_gcloud 
    - ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
  tags:
    - gcloud
