---
- name: Install cosign
  become: false
  ansible.builtin.command: "go install github.com/sigstore/cosign/v2/cmd/cosign@{{ cosign_version }}"
  tags: [cosign, go, packages]

- name: Install fx
  become: false
  ansible.builtin.command: "go install github.com/antonmedv/fx@{{ fx_version }}"
  tags: [fx, go, packages]

- name: Install yq
  become: false
  ansible.builtin.command: "go install github.com/mikefarah/yq/v4@{{ yq_version }}"
  tags: [yq, go, packages]

- name: Install golangci-lint
  become: false
  ansible.builtin.command: "go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@{{ golangci_lint_version }}"
  tags: [golangci_lint, go, packages]

- name: Install jump
  become: false
  ansible.builtin.command: "go install github.com/gsamokovarov/jump@{{ jump_version }}"
  tags: [jump, go, packages]

- name: Install kubectx
  become: false
  ansible.builtin.command: "go install github.com/ahmetb/kubectx/cmd/kubectx@{{ kubectx_version }}"
  tags: [kubectx, go, packages]

- name: Install kubens
  become: false
  ansible.builtin.command: "go install github.com/ahmetb/kubectx/cmd/kubens@{{ kubectx_version }}"
  tags: [kubectx, kubens, go, packages]

- name: Install sops
  become: false
  ansible.builtin.command: "go install github.com/getsops/sops/v3/cmd/sops@{{ sops_version }}"
  tags: [sops, go, packages]

- name: Install sc
  become: false
  ansible.builtin.command: "go install github.com/soerenschneider/sc@{{ sc_version }}"
  tags: [sc, go, packages]

- name: Install terragrunt
  become: false
  block:
    - name: Clone repo
      ansible.builtin.git:
        repo: "https://github.com/gruntwork-io/terragrunt"
        dest: "{{ sw_dir }}/terragrunt"
        version: "{{ terragrunt_version }}"

    - name: Build terragrunt
      ansible.builtin.command:
        cmd: "make build"
        chdir: "{{ sw_dir }}/terragrunt"

    - name: Copy file
      ansible.builtin.copy:
        src: "{{ sw_dir }}/terragrunt/terragrunt"
        dest: "/home/{{ user }}/bin/terragrunt"
        mode: "0755"
  tags: [terragrunt, go, packages]
