---
- name: Checkout kubectx
  become: false
  git:
    repo: 'https://github.com/ahmetb/kubectx.git'
    dest: '{{ sw_dir }}/kubectx'
    version: '{{ kubectx_version | default("master") }}'
  register: git_clone
  tags: kubernetes

- name: Set link to kubectx
  become: false
  file:
    src: "{{ sw_dir }}/kubectx/kubectx"
    path: "/home/soeren/bin/kubectx"
    state: link
  tags: kubernetes

- name: Set link to kubectx completion
  become: false
  file:
    src: "{{ sw_dir }}/kubectx/completion/kubectx.zsh"
    path: "/home/soeren/.oh-my-zsh/completions/_kubectx.zsh"
    state: link
  tags: kubernetes

- name: Set link to kubens
  become: false
  file:
    src: "{{ sw_dir }}/kubectx/kubens"
    path: "/home/soeren/bin/kubens"
    state: link
  tags: kubernetes

- name: Set link to kubens completion
  become: false
  file:
    src: "{{ sw_dir }}/kubectx/completion/kubens.zsh"
    path: "/home/soeren/.oh-my-zsh/completions/_kubens.zsh"
    state: link
  tags: kubernetes
