---
- name: Checkout nb
  become: false
  git:
    repo: 'https://github.com/xwmx/nb.git'
    dest: '{{ sw_dir }}/nb'
    version: '{{ nb_version | default("master") }}'
  register: git_clone
  tags:
    - software
    - nb

- name: Set link to nb
  become: false
  file:
    src: "{{ sw_dir }}/nb/nb"
    path: "/home/soeren/bin/nb"
    state: link
  tags:
    - software
    - nb
