---
- name: Make sure git directories exists
  become: false
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "{{ gitlab_dir }}"
    - "{{ github_dir }}"
  tags: repos

- name: Set correct git config
  ansible.builtin.copy:
    content: |
      [user]
      email = 2378192-soerenschneider@users.noreply.gitlab.com
    dest: "{{ gitlab_dir }}/.gitconfig"
  tags: repos

- include_tasks: repos_checkout.yml
  with_items: "{{ repos }}"
  tags: repos

- name: Install dotfiles
  command: sh ./install.sh
  become: false
  args:
    chdir: "{{ github_dir }}/dotfiles"
  register: output
  tags: repos

- name: Install scripts
  command: make install
  become: false
  args:
    chdir: "{{ github_dir }}/scripts"
  tags: repos

- name: Copy circadian-daemon config
  ansible.builtin.copy:
    content: |
      {{ circadian_config | to_nice_json }}
    dest: "/home/{{ user }}/.config/circadian-daemon.json"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: "0644"
  become: false
  tags: repos

- name: Create pass link to repo
  become: false
  file:
    src: "{{ gitlab_dir }}/abrakadabra"
    dest: "/home/{{ user }}/.password-store"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  tags: repos
