---
- name: Make sure git directories exists
  become: false
  file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    owner: "{{ user }}"
    group: "{{ user }}"
  with_items:
    - "{{ gitlab_dir }}"
    - "{{ github_dir }}"
  tags: repos

- include_tasks: repos_checkout.yml
  with_items: "{{ repos }}"
  tags: repos

- name: Install dotfiles
  command: sh ./install.sh
  become: false
  args:
    chdir: "{{ gitlab_dir }}/dotfiles"
  register: output
  tags: repos

- name: Create pass link to repo
  become: false
  file:
    src: "{{ gitlab_dir }}/abrakadabra"
    dest: "/home/{{ user }}/.password-store"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  tags: repos
